export const ADD_STAFFS = "ADD_STAFFS";
export const STAFFS_LOADING = "STAFFS_LOADING";
export const STAFFS_FAILED = "STAFFS_FAILED";
export const POST_STAFFS = "POST_STAFFS";
export const ADD_STAFF = "ADD_STAFF";

export const ADD_DEPARTMENTS = "ADD_DEPARTMENTS";
export const DEPARTMENTS_LOADING = "DEPARTMENTS_LOADING";
export const DEPARTMENTS_FAILED = "DEPARTMENTS_FAILED";

export const ADD_DEPARTMENTSBYID = "ADD_DEPARTMENTSBYID";
export const DEPARTMENTSBYID_LOADING = "DEPARTMENTSBYID_LOADING";
export const DEPARTMENTSBYID_FAILED = "DEPARTMENTSBYID_FAILED";

export const ADD_SALARYS = "ADD_SALARYS";
export const SALARYS_LOADING = "SALARY_LOADING";
export const SALARYS_FAILED = "SALARYS_FAILED";
